### PR TITLE
Nterl0k - T1649 - ESC1 abuse with certify/certipy toolkits

### PR DESCRIPTION
**Pull request by nterl0k**
Uploading data for upcoming Certipy/ESC1 abuse detection.

### CODE REVIEW

**Review by patel-bhavin — APPROVED** [review]

**Comment by patel-bhavin** [comment]
@nterl0k : we don't support multiple log types in a single. Can you split the `datasets/attack_techniques/T1649/certify_abuse/certify_esc1_abuse.log` LFS files into separate files based on what sourcetype it is and then update the links in the detection.yml

**Review by patel-bhavin — CHANGES_REQUESTED** [review]
comments added above

**Comment by nterl0k** [comment]
> @nterl0k : we don't support multiple log types in a single. Can you split the `datasets/attack_techniques/T1649/certify_abuse/certify_esc1_abuse.log` LFS files into separate files based on what sourcetype it is and then update the links in the detection.yml

@patel-bhavin  Not a problem at all, I will know better in the future. I'll get to work on splitting / updating based on sourcetype.

**Comment by patel-bhavin** [comment]
Thats awesome! i did some minor updates and created a new PR based on this which has  now been merged. Will now check if it passes testing for this PR : https://github.com/splunk/security_content/pull/2787

**Comment by patel-bhavin** [comment]
Thank you for updating the PR!

**Pull request closed without merging**
