### PR TITLE
Nterl0k - Goot Loader Malware w/ Partial TTPs

### PR DESCRIPTION
**Pull request by nterl0k**
Upload for incoming detection builds.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
@nterl0k : Hello, thank you for the PR. Can you add a yml file in the `partial_ttps` describing the data, how it was generated? 
Eg: https://github.com/splunk/attack_data/blob/master/datasets/attack_techniques/T1003.001/atomic_red_team/atomic_red_team.yml

**Comment by nterl0k** [comment]
Can do, didn't realize we still needed the description ymls.

I'll craft one and upload shortly.
________________________________

**Comment by nterl0k** [comment]
yml added, edit/update as you need to.

**Comment by patel-bhavin** [comment]
perfect! this is great. thank you for being so prompt! @nterl0k

**Review by patel-bhavin — APPROVED** [review]

**Pull request merged**
