### PR TITLE
Nterl0k pingid mfa

### PR DESCRIPTION
**Pull request by nterl0k**
PingID/PingOne dataset for upcoming detection PR.

### CODE REVIEW

**Comment by patel-bhavin** [comment]
@nterl0k : can you add a yaml file explaining this dataset 

EG: https://github.com/splunk/attack_data/blob/master/datasets/attack_techniques/T1003.001/atomic_red_team/atomic_red_team.yml

**Comment by nterl0k** [comment]
Oversight on my part, will do directly. Sorry about that.



Regards,

Steven.



-------- Original message --------
From: Bhavin Patel ***@***.***>
Date: 10/23/23 3:11 PM (GMT-05:00)
To: splunk/attack_data ***@***.***>
Cc: Steven Dick ***@***.***>, Mention ***@***.***>
Subject: Re: [splunk/attack_data] Nterl0k pingid mfa (PR #846)


@nterl0k<https://github.com/nterl0k> : can you add a yaml file explaining this dataset

EG: https://github.com/splunk/attack_data/blob/master/datasets/attack_techniques/T1003.001/atomic_red_team/atomic_red_team.yml

**Comment by patel-bhavin** [comment]
Also, these datasets are probably not uploaded via git lfs , upload it via lfs so that it is available as a media. Thank you!

**Comment by nterl0k** [comment]
@patel-bhavin uploaded a dataset yaml and reuploaded the log files.

**Review by patel-bhavin — APPROVED** [review]

**Comment by patel-bhavin** [comment]
minor yaml changes and the PR looks good, merged for testing the detections

**Pull request merged**
